import type { EventSetDefinition, FormDesignerSchema, FormQueueRecord, InstructorEvent, RuntimeSection, TaskRatingValue } from "./types";

export const emptyAssessment = (): TaskRatingValue => ({
    ratings: {
        safety: null,
        technical: null,
        procedures: null,
        crew: null,
    },
    comments: "",
});

export const syntheticEventSets: EventSetDefinition[] = [
    {
        id: "es-flight-management",
        code: "ES-201",
        title: "Flight management under changing conditions",
        phase: "Scenario segment 1",
        objective: "Manage a changing operational picture while maintaining safe margins and a shared crew plan.",
        repeatCap: 2,
        required: true,
    },
    {
        id: "es-systems-prioritization",
        code: "ES-204",
        title: "Systems prioritization and recovery",
        phase: "Scenario segment 2",
        objective: "Identify the highest-priority cues, coordinate the response, and establish a stable outcome.",
        repeatCap: 2,
        required: true,
    },
    {
        id: "es-arrival-planning",
        code: "ES-208",
        title: "Arrival planning and workload management",
        phase: "Scenario segment 3",
        objective: "Build, communicate, and adapt an arrival plan within the available time and resources.",
        repeatCap: 1,
        required: true,
    },
];

export const initialRuntimeSections: RuntimeSection[] = [
    {
        id: "event-context",
        label: "Event context",
        shortLabel: "Context",
        requiredCount: 4,
        completedCount: 4,
        status: "complete",
    },
    {
        id: "event-sets",
        label: "Event set assessments",
        shortLabel: "Event sets",
        requiredCount: 12,
        completedCount: 3,
        status: "in-progress",
    },
    {
        id: "overall-assessment",
        label: "Overall assessment",
        shortLabel: "Overall",
        requiredCount: 3,
        completedCount: 1,
        status: "in-progress",
    },
    {
        id: "signatures",
        label: "Signatures",
        shortLabel: "Sign",
        requiredCount: 2,
        completedCount: 0,
        status: "not-started",
    },
];

export const initialDesignerSchema: FormDesignerSchema = {
    id: "form-b747-cq-001",
    name: "B747 AQP CQ — Evaluation Record",
    program: "B747 AQP CQ",
    version: "Draft 0.4",
    status: "draft",
    sections: [
        {
            id: "section-event",
            title: "Event context",
            description: "Read-only event and roster details are bound when the form is opened.",
            fields: [
                {
                    id: "field-event-code",
                    type: "short-text",
                    label: "Event code",
                    helpText: "Resolved from the scheduled event.",
                    required: true,
                },
                {
                    id: "field-session-note",
                    type: "long-text",
                    label: "Session context",
                    helpText: "Record context that materially affected the assessment.",
                    required: false,
                },
            ],
        },
        {
            id: "section-assessment",
            title: "Assessment",
            description: "Only approved assessment controls can be added to this section.",
            fields: [
                {
                    id: "field-event-set",
                    type: "event-set",
                    label: "Event set assessment",
                    helpText: "Repeat attempts remain visible in the final record.",
                    required: true,
                },
                {
                    id: "field-rating",
                    type: "rating-matrix",
                    label: "Overall task rating",
                    required: true,
                },
            ],
        },
        {
            id: "section-signatures",
            title: "Attestation",
            description: "Signatures are applied only after review.",
            fields: [
                {
                    id: "field-instructor-signature",
                    type: "signature",
                    label: "Instructor attestation",
                    required: true,
                },
            ],
        },
    ],
};

export const syntheticQueueRecords: FormQueueRecord[] = [
    {
        id: "FRM-260730-014",
        eventCode: "EVT-7412",
        program: "B747 AQP CQ",
        participant: "Participant 1842",
        instructor: "Instructor 046",
        sessionDate: "Jul 30, 2026",
        submittedAt: "Today, 15:42",
        status: "submitted",
        completeness: 100,
        syncState: "synced",
        flags: ["Low rating comment"],
    },
    {
        id: "FRM-260730-011",
        eventCode: "EVT-7409",
        program: "B747 AQP CQ",
        participant: "Participant 3176",
        instructor: "Instructor 112",
        sessionDate: "Jul 30, 2026",
        submittedAt: "Today, 14:18",
        status: "qc-returned",
        completeness: 100,
        syncState: "synced",
        flags: ["Signature clarification"],
    },
    {
        id: "FRM-260730-009",
        eventCode: "EVT-7407",
        program: "B747 AQP CQ",
        participant: "Participant 5229",
        instructor: "Instructor 046",
        sessionDate: "Jul 30, 2026",
        status: "awaiting-signature",
        completeness: 92,
        syncState: "pending",
        flags: [],
    },
    {
        id: "FRM-260729-028",
        eventCode: "EVT-7388",
        program: "B747 AQP CQ",
        participant: "Participant 0964",
        instructor: "Instructor 083",
        sessionDate: "Jul 29, 2026",
        status: "sync-conflict",
        completeness: 88,
        syncState: "conflict",
        flags: ["Two device versions", "Missing overall outcome"],
    },
    {
        id: "FRM-260729-023",
        eventCode: "EVT-7384",
        program: "B747 AQP CQ",
        participant: "Participant 6631",
        instructor: "Instructor 083",
        sessionDate: "Jul 29, 2026",
        submittedAt: "Yesterday, 18:06",
        status: "qc-approved",
        completeness: 100,
        syncState: "synced",
        flags: [],
    },
];

export const syntheticInstructorEvents: InstructorEvent[] = [
    {
        id: "event-7412",
        eventCode: "EVT-7412",
        title: "CQ simulator evaluation",
        program: "B747 AQP CQ",
        version: "2026.2",
        dateLabel: "Today · Jul 30",
        timeLabel: "18:30–22:15",
        location: "Training Center · Bay 4",
        participantCount: 2,
        formCount: 2,
        openFormCount: 1,
        offlineState: "ready",
        brief: {
            objective: "Evaluate safe, coordinated performance across a changing line-oriented scenario.",
            emphasisItems: ["Shared mental model", "Workload prioritization", "Stable recovery criteria"],
            resources: ["Scenario overview", "Evaluation anchors", "Event roster"],
            note: "Synthetic demonstration event. Confirm the roster and device pack before leaving connectivity.",
        },
    },
    {
        id: "event-7426",
        eventCode: "EVT-7426",
        title: "CQ maneuver validation",
        program: "B747 AQP CQ",
        version: "2026.2",
        dateLabel: "Tomorrow · Jul 31",
        timeLabel: "08:00–11:40",
        location: "Training Center · Bay 2",
        participantCount: 2,
        formCount: 2,
        openFormCount: 0,
        offlineState: "update-available",
        brief: {
            objective: "Observe consistent application of planning, execution, and recovery behaviors.",
            emphasisItems: ["Threat review", "Procedure discipline", "Crew communication"],
            resources: ["Maneuver outline", "Evaluation anchors", "Event roster"],
            note: "A newer roster snapshot is available. Refresh the pack before the event.",
        },
    },
    {
        id: "event-7480",
        eventCode: "EVT-7480",
        title: "CQ scenario observation",
        program: "B747 AQP CQ",
        version: "2026.2",
        dateLabel: "Mon · Aug 3",
        timeLabel: "13:15–17:00",
        location: "Training Center · Bay 1",
        participantCount: 2,
        formCount: 2,
        openFormCount: 0,
        offlineState: "not-downloaded",
        brief: {
            objective: "Capture evidence against the approved behavioral dimensions during a complete scenario.",
            emphasisItems: ["Decision quality", "Technical accuracy", "Procedural consistency"],
            resources: ["Scenario overview", "Event roster"],
            note: "Offline pack has not been downloaded.",
        },
    },
];
